// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel1;
void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Keyboard3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label12;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
void ui_event_Image15(lv_event_t * e);
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Arc1;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label199;
extern lv_obj_t * ui_Label198;
extern lv_obj_t * ui_Label197;
extern lv_obj_t * ui_Label231;
extern lv_obj_t * ui_Label230;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Checkbox3;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
void ui_event_Screen7(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Spinbox1;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Spinbox2;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Spinbox3;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
void ui_event_Screen8(lv_event_t * e);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Checkbox5;
extern lv_obj_t * ui_Label29;
void ui_event_TextArea5(lv_event_t * e);
extern lv_obj_t * ui_TextArea5;
void ui_event_TextArea6(lv_event_t * e);
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_Keyboard4;
// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
void ui_event_Screen9(lv_event_t * e);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Container1;
// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
void ui_event_Screen10(lv_event_t * e);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_Chart1;
// SCREEN: ui_Screen11
void ui_Screen11_screen_init(void);
void ui_event_Screen11(lv_event_t * e);
extern lv_obj_t * ui_Screen11;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_group_289_png);    // assets/Group 289.png
LV_IMG_DECLARE(ui_img_group_1_png);    // assets/Group 1.png
LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_1993735377);    // assets/fire (1).png
LV_IMG_DECLARE(ui_img_glass_thermometer_png);    // assets/glass thermometer.png
LV_IMG_DECLARE(ui_img_location_icon_png);    // assets/location icon.png
LV_IMG_DECLARE(ui_img_timer_png);    // assets/timer.png
LV_IMG_DECLARE(ui_img_to_do_png);    // assets/To Do.png
LV_IMG_DECLARE(ui_img_heart_with_pulse_png);    // assets/Heart with Pulse.png
LV_IMG_DECLARE(ui_img_pulse_oximeter_png);    // assets/Pulse Oximeter.png
LV_IMG_DECLARE(ui_img_250249727);    // assets/Icons (1).png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/temp.png
LV_IMG_DECLARE(ui_img_p_png);    // assets/p.png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets/Group 2.png
LV_IMG_DECLARE(ui_img_group_290_png);    // assets/Group 290.png
LV_IMG_DECLARE(ui_img_spo2_png);    // assets/spO2.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font10);
LV_FONT_DECLARE(ui_font_Font11);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);
LV_FONT_DECLARE(ui_font_Font4);
LV_FONT_DECLARE(ui_font_Font5);
LV_FONT_DECLARE(ui_font_Font6);
LV_FONT_DECLARE(ui_font_Font7);
LV_FONT_DECLARE(ui_font_Font8);
LV_FONT_DECLARE(ui_font_Font9);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
