// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -134);
    lv_obj_set_y(ui_Label21, -171);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Calories");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Font7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel5, 426);
    lv_obj_set_height(ui_Panel5, 299);
    lv_obj_set_x(ui_Panel5, 2);
    lv_obj_set_y(ui_Panel5, 36);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel5, lv_color_hex(0xFFCE48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel5, 56, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -65);
    lv_obj_set_y(ui_Label23, -72);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Steps");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);
        ui_Label230 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label230, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label230, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label230, 15);
    lv_obj_set_y(ui_Label230, -72);
    lv_obj_set_align(ui_Label230, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label230, "Steps");
    lv_obj_set_style_text_color(ui_Label230, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label230, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label230, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);
        ui_Label231 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label231, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label231, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label231, 105);
    lv_obj_set_y(ui_Label231, 62);
    lv_obj_set_align(ui_Label231, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label231, "Steps");
    lv_obj_set_style_text_color(ui_Label231, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label231, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label231, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -23);
    lv_obj_set_y(ui_Label20, 62);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Calories Burned");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x626262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image24, &ui_img_group_1_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image24, -167);
    lv_obj_set_y(ui_Image24, -36);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image24, 400);

    ui_Image25 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image25, &ui_img_1993735377);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image25, -166);
    lv_obj_set_y(ui_Image25, 94);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image25, 500);

    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}
