// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox1 = lv_checkbox_create(ui_Screen6);
    lv_checkbox_set_text(ui_Checkbox1, "Done");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, 171);
    lv_obj_set_y(ui_Checkbox1, -146);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_transform_zoom(ui_Checkbox1, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox2 = lv_checkbox_create(ui_Screen6);
    lv_checkbox_set_text(ui_Checkbox2, "Done");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, 171);
    lv_obj_set_y(ui_Checkbox2, -32);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_transform_zoom(ui_Checkbox2, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox3 = lv_checkbox_create(ui_Screen6);
    lv_checkbox_set_text(ui_Checkbox3, "Done");
    lv_obj_set_width(ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox3, 173);
    lv_obj_set_y(ui_Checkbox3, 81);
    lv_obj_set_align(ui_Checkbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_transform_zoom(ui_Checkbox3, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextArea1, 333);
    lv_obj_set_height(ui_TextArea1, 71);
    lv_obj_set_x(ui_TextArea1, -79);
    lv_obj_set_y(ui_TextArea1, -139);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



    ui_TextArea2 = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextArea2, 333);
    lv_obj_set_height(ui_TextArea2, 71);
    lv_obj_set_x(ui_TextArea2, -76);
    lv_obj_set_y(ui_TextArea2, -32);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");



    ui_TextArea3 = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextArea3, 333);
    lv_obj_set_height(ui_TextArea3, 71);
    lv_obj_set_x(ui_TextArea3, -76);
    lv_obj_set_y(ui_TextArea3, 90);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");



    ui_Keyboard2 = lv_keyboard_create(ui_Screen6);
    lv_obj_set_width(ui_Keyboard2, 660);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, -31);
    lv_obj_set_y(ui_Keyboard2, 166);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea1);

}
