// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox4 = lv_checkbox_create(ui_Screen8);
    lv_checkbox_set_text(ui_Checkbox4, "Done");
    lv_obj_set_width(ui_Checkbox4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox4, 133);
    lv_obj_set_y(ui_Checkbox4, -57);
    lv_obj_set_align(ui_Checkbox4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox4, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox5 = lv_checkbox_create(ui_Screen8);
    lv_checkbox_set_text(ui_Checkbox5, "Done");
    lv_obj_set_width(ui_Checkbox5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox5, 134);
    lv_obj_set_y(ui_Checkbox5, 78);
    lv_obj_set_align(ui_Checkbox5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox5, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -154);
    lv_obj_set_y(ui_Label29, -171);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Set Reminder");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_Font7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea5 = lv_textarea_create(ui_Screen8);
    lv_obj_set_width(ui_TextArea5, 333);
    lv_obj_set_height(ui_TextArea5, 89);
    lv_obj_set_x(ui_TextArea5, -114);
    lv_obj_set_y(ui_TextArea5, -55);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea5, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextArea6 = lv_textarea_create(ui_Screen8);
    lv_obj_set_width(ui_TextArea6, 333);
    lv_obj_set_height(ui_TextArea6, 89);
    lv_obj_set_x(ui_TextArea6, -110);
    lv_obj_set_y(ui_TextArea6, 73);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea6, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea6, &ui_font_Font11, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Keyboard4 = lv_keyboard_create(ui_Screen8);
    lv_obj_set_width(ui_Keyboard4, 614);
    lv_obj_set_height(ui_Keyboard4, 120);
    lv_obj_set_x(ui_Keyboard4, 2);
    lv_obj_set_y(ui_Keyboard4, 179);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Keyboard4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard4, lv_color_hex(0xFFCE48), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard4, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea6, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard4, ui_TextArea5);
    lv_obj_add_event_cb(ui_Screen8, ui_event_Screen8, LV_EVENT_ALL, NULL);

}
